src/Entity/ListeFrais.php
<?php

namespace App\Entity;

use App\Repository\ListeFraisRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ListeFraisRepository::class)]
class ListeFrais
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column]
    private ?int $equipement = null;

    #[ORM\Column(length: 255)]
    private ?string $missions = null;

    #[ORM\Column]
    private ?int $repas = null;

    #[ORM\Column(length: 255)]
    private ?string $divers = null;

    #[ORM\Column]
    private ?int $TVA = null;

    #[ORM\Column]
    private ?int $debut_km = null;

    #[ORM\Column]
    private ?int $fin_km = null;

    #[ORM\Column]
    private ?int $montant_total = null;

    #[ORM\Column(nullable: true)]
    private ?int $forfait_kilometrique = null;
    

    #[ORM\ManyToOne(inversedBy: 'NoteFrais')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Frais $frais = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getEquipement(): ?int
    {
        return $this->equipement;
    }

    public function setEquipement(int $equipement): static
    {
        $this->equipement = $equipement;

        return $this;
    }

    public function getMissions(): ?string
    {
        return $this->missions;
    }

    public function setMissions(string $missions): static
    {
        $this->missions = $missions;

        return $this;
    }

    public function getRepas(): ?int
    {
        return $this->repas;
    }

    public function setRepas(int $repas): static
    {
        $this->repas = $repas;

        return $this;
    }

    public function getDivers(): ?string
    {
        return $this->divers;
    }

    public function setDivers(string $divers): static
    {
        $this->divers = $divers;

        return $this;
    }

    public function getTVA(): ?int
    {
        return $this->TVA;
    }

    public function setTVA(int $TVA): static
    {
        $this->TVA = $TVA;

        return $this;
    }

    public function getDebutKm(): ?int
    {
        return $this->debut_km;
    }

    public function setDebutKm(int $debut_km): static
    {
        $this->debut_km = $debut_km;

        return $this;
    }

    public function getFinKm(): ?int
    {
        return $this->fin_km;
    }

    public function setFinKm(int $fin_km): static
    {
        $this->fin_km = $fin_km;

        return $this;
    }

    public function getMontantTotal(): ?int
    {
        return $this->montant_total;
    }

    public function setMontantTotal(int $montant_total): static
    {
        $this->montant_total = $montant_total;

        return $this;
    }

    public function getForfaitKilometrique(): ?int
    {
        return $this->forfait_kilometrique;
    }

    public function setForfaitKilometrique(int $forfait_kilometrique): static
    {
        $this->forfait_kilometrique = $forfait_kilometrique;

        return $this;
    }

    public function getFrais(): ?Frais
    {
        return $this->frais;
    }

    public function setFrais(?Frais $frais): static
    {
        $this->frais = $frais;

        return $this;
    }
}

src/Controller/ListeFraisController.php
<?php

namespace App\Controller;

use App\Entity\Frais;
use App\Entity\ListeFrais;
use App\Form\ListeFrais1Type;
use App\Repository\FraisRepository;
use App\Repository\ListeFraisRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;

#[Route('/note/{noteId}/liste/frais')]
class ListeFraisController extends AbstractController
{
    private EntityManagerInterface $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }
    #[Route('/', name: 'app_liste_frais_index', methods: ['GET'])]
    public function index(int $noteId, ListeFraisRepository $listeFraisRepository, UserInterface $user): Response
    {
        $liste_frais = $listeFraisRepository->findBy(['frais' => $noteId]);

        return $this->render('liste_frais/index.html.twig', [
            'liste_frais' => $liste_frais,
            'noteId' => $noteId
        ]);
    }

    #[Route('/new', name: 'app_liste_frais_new', methods: ['GET', 'POST'])]
    public function new(Request $request, int $noteId, EntityManagerInterface $entityManager): Response
    {
        $listeFrai = new ListeFrais();
        $form = $this->createForm(ListeFrais1Type::class, $listeFrai);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $listeFrai->setFrais($this->entityManager->getReference(Frais::class, $noteId));
            $entityManager->persist($listeFrai);
            $entityManager->flush();

            return $this->redirectToRoute('app_liste_frais_index', ['noteId' => $noteId], Response::HTTP_SEE_OTHER);
        }

        return $this->render('liste_frais/new.html.twig', [
            'liste_frai' => $listeFrai,
            'form' => $form,
            'noteId' => $noteId
        ]);
    }

    #[Route('/{id}', name: 'app_liste_frais_show', methods: ['GET'])]
    public function show(int $noteId, ListeFrais $listeFrai): Response
    {
        return $this->render('liste_frais/show.html.twig', [
            'liste_frai' => $listeFrai,
            'noteId' => $noteId
        ]);
    }

    #[Route('/{id}/edit', name: 'app_liste_frais_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, int $noteId, ListeFrais $listeFrai, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ListeFrais1Type::class, $listeFrai);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_liste_frais_index', ['noteId' => $noteId], Response::HTTP_SEE_OTHER);
        }

        return $this->render('liste_frais/edit.html.twig', [
            'liste_frai' => $listeFrai,
            'form' => $form,
            'noteId' => $noteId

        ]);
    }

    #[Route('/{id}', name: 'app_liste_frais_delete', methods: ['POST'])]
    public function delete(Request $request,int $noteId, ListeFrais $listeFrai, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$listeFrai->getId(), $request->getPayload()->get('_token'))) {
            $entityManager->remove($listeFrai);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_liste_frais_index', ['noteId' => $noteId], Response::HTTP_SEE_OTHER);
    }
}

templates/liste_frais/_delete_form.html.twig
<form method="post" action="{{ path('app_liste_frais_delete', {'id': liste_frai.id, 'noteId': noteId}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ liste_frai.id) }}">
    <button class="btn btn-danger button">Delete</button>
</form>

templates/liste_frais/_form.html.twig
<link rel="stylesheet" href="{{ asset('styles/edit_form.css') }}">
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/liste_frais/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit ListeFrais{% endblock %}

{% block body %}
<div style="text-align: center; margin-top: 1em;">
    <h1>Edit ListeFrais</h1>
    </div>
    {{ include('liste_frais/_form.html.twig', {'button_label': 'Update'}) }}
    {{ include('liste_frais/_delete_form.html.twig') }}
    {#<a href="{{ path('app_liste_frais_index', {'noteId': noteId}) }}">back to list</a>#}
{% endblock %}

templates/liste_frais/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}ListeFrais index{% endblock %}

{% block body %}
    <div class="container">
        <h1 class="my-4">Liste Frais</h1>

        <div class="table-responsive">
            <table id="TableListeDeFrais" class="table table-striped">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Date</th>
                        <th>Description</th>
                        <th>Equipement</th>
                        <th>Missions</th>
                        <th>Repas</th>
                        <th>Divers</th>
                        <th>TVA</th>
                        <th>Debut Km</th>
                        <th>Fin Km</th>
                        <th>Montant Total Kilometrique</th>
                        <th>Forfait Kilometrique</th>
                        <th class="exclude-from-excel">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for liste_frai in liste_frais %}
                        <tr>
                            <td>{{ liste_frai.id }}</td>
                            <td>{{ liste_frai.date ? liste_frai.date|date('Y-m-d') : '' }}</td>
                            <td>{{ liste_frai.description }}</td>
                            <td>{{ liste_frai.equipement }}</td>
                            <td>{{ liste_frai.missions }}</td>
                            <td>{{ liste_frai.repas }}</td>
                            <td>{{ liste_frai.divers }}</td>
                            <td>{{ liste_frai.TVA }}</td>
                            <td>{{ liste_frai.debutKm }}</td>
                            <td>{{ liste_frai.finKm }}</td>
                            <td>{{ liste_frai.montantTotal }}</td>
                            <td>{{ liste_frai.forfaitKilometrique }}</td>
                            <td class="exclude-from-excel">
                                <a href="{{ path('app_liste_frais_show', {'id': liste_frai.id, 'noteId': noteId}) }}" class="btn btn-primary">Show</a>
                                <a href="{{ path('app_liste_frais_edit', {'id': liste_frai.id, 'noteId': noteId}) }}" class="btn btn-warning">Edit</a>
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="13" class="text-center">No records found</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <a href="{{ path('app_liste_frais_new', {'noteId': noteId}) }}" class="btn btn-success">Create new</a>
    </div>
{% endblock %}

templates/liste_frais/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Note de frais{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('styles/listefrais.css') }}">
{% endblock %}

{% block body %}
<div class="container">

    {{ form_start(form) }}
    <div class="text-center">
        <h1 class="h1 mb-3 font-weight-normal color = ''">Créer Note de Frais</h1>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <h1 class="h4 mb-2 mt-2 font-weight-normal color = ''">Date</h1>
                {{ form_widget(form.date, {'attr': {'class': 'form-control'}}) }}
            </div>
            <div class="form-group">
                <h1 class="h4 mb-2 mt-2 font-weight-normal color = ''">Equipement</h1>
                {{ form_widget(form.equipement, {'attr': {'class': 'form-control'}}) }}
            </div>
            <div class="form-group">
                <h1 class="h4 mb-2 mt-2 font-weight-normal color = ''">Repas</h1>
                {{ form_widget(form.repas, {'attr': {'class': 'form-control'}}) }}
            </div>
            <div class="form-group">
                <h1 class="h4 mb-2 mt-2 font-weight-normal color = ''">TVA</h1>
                {{ form_widget(form.TVA, {'attr': {'class': 'form-control'}}) }}
            </div>
            <div class="form-group">
                <h1 class="h4 mb-2 mt-2 font-weight-normal color = ''">Debut Km</h1>
                {{ form_widget(form.debut_km, {'attr': {'class': 'form-control'}}) }}
            </div>
            <div class="form-group">
                <h1 class="h4 mb-2 mt-2 font-weight-normal color = ''">Fin Km</h1>
                {{ form_widget(form.fin_km, {'attr': {'class': 'form-control'}}) }}
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <h1 class="h4 mb-2 mt-2 font-weight-normal color = ''">Description</h1>
                {{ form_widget(form.description, {'attr': {'class': 'form-control'}}) }}
            </div>
            <div class="form-group">
                <h1 class="h4 mb-2 mt-2 font-weight-normal color = ''">Missions</h1>
                {{ form_widget(form.missions, {'attr': {'class': 'form-control'}}) }}
            </div>
            <div class="form-group">
                <h1 class="h4 mb-2 mt-2 font-weight-normal color = ''">Divers</h1>
                {{ form_widget(form.divers, {'attr': {'class': 'form-control'}}) }}
            </div>
            <div class="form-group">
                <h1 class="h4 mb-2 mt-2 font-weight-normal color = ''">Montant Total Kilometrique</h1>
                {{ form_widget(form.montant_total, {'attr': {'class': 'form-control'}}) }}
            </div>
            <div class="form-group">
                <h1 class="h4 mb-2 mt-2 font-weight-normal color = ''">Forfait Kilométrique </h1>
                {{ form_widget(form.forfait_kilometrique, {'attr': {'class': 'form-control', 'value': '0.456 € < 20 km ou 0.318 € > 20 km'}, 'disabled': true}) }}
            </div>
        </div>
    </div>

    <button class="btn btn-primary button">Envoyer</button>
    {{ form_end(form) }}
</div>
{% endblock %}

templates/liste_frais/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}ListeFrais{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('styles/show_1.css') }}">
{% endblock %}


{% block body %}

    <div class="container">
    <h1>ListeFrais</h1>
    <table class="table table-striped">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ liste_frai.id }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ liste_frai.date ? liste_frai.date|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ liste_frai.description }}</td>
            </tr>
            <tr>
                <th>Equipement</th>
                <td>{{ liste_frai.equipement }}</td>
            </tr>
            <tr>
                <th>Missions</th>
                <td>{{ liste_frai.missions }}</td>
            </tr>
            <tr>
                <th>Repas</th>
                <td>{{ liste_frai.repas }}</td>
            </tr>
            <tr>
                <th>Divers</th>
                <td>{{ liste_frai.divers }}</td>
            </tr>
            <tr>
                <th>TVA</th>
                <td>{{ liste_frai.TVA }}</td>
            </tr>
            <tr>
                <th>Debut_km</th>
                <td>{{ liste_frai.debutKm }}</td>
            </tr>
            <tr>
                <th>Fin_km</th>
                <td>{{ liste_frai.finKm }}</td>
            </tr>
            <tr>
                <th>Montant_total_Kilometrique</th>
                <td>{{ liste_frai.montantTotal }}</td>
            </tr>
            <tr>
                <th>Forfait_kilometrique</th>
                <td>{{ liste_frai.forfaitKilometrique }}</td>
            </tr>
        </tbody>
    </table>

    {#<a href="{{ path('app_liste_frais_edit', {'id': liste_frai.id, 'noteId': noteId}) }}">edit</a>#}

    {{ include('liste_frais/_delete_form.html.twig') }}
    </div>
{% endblock %}